### ISSUE TITLE
ember install ember-cli-slick installs another addon with the same name

### ISSUE THREAD

**Issue by 4xposed** [igorpreston/ember-cli-slick#1]
When running:
```
ember install ember-cli-slick
```
instead this addon it installs this other one with the same name: https://github.com/laantorchaweb/ember-cli-slick

any way to force to install this one?

**Comment by igorpreston** [comment]
@4xposed hey thank you for your interest. This addon is still in development and has not been released yet on npm so technically you cannot install it with ember install command. Though you can install it directly from git repository using npm install.

I have not fixed dependency installation issue yet. Unfortunately, the name of the addon was taken by someone else already so I will be changing it to some other name.

**Comment by igorpreston** [comment]
@4xposed hey if you are still interested, I now released the carousel here: https://github.com/igorpreston/ember-cli-slick-carousel
